###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '8001:8025'

    postgres:
        image: 'postgres:15-alpine'
        working_dir: /slimFramework
        volumes:
            - '.:/slimFramework'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=db
        ports:
            - '8004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /slimFramework
        volumes:
            - '.:/slimFramework'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8800:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /slimFramework
        volumes:
            - '.:/slimFramework'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
